SELECT *
FROM	TWEEDLEDEER,
		POSITION,
		SHIP_ROSTER,
		MEDAL,
		SPACESHIP,
		RAID,
		PRISONER,
		PLANET,
		STAR
WHERE	POSITION.PositionName = TWEEDLEDEER.Position
AND		TWEEDLEDEER.Tweedle_No = SHIP_ROSTER.Tweedle_No
AND		MEDAL.Medal = SHIP_ROSTER.Medal
AND		SPACESHIP.ShipRego_No = SHIP_ROSTER.ShipRego_No
AND		SPACESHIP.ShipRego_No = RAID.ShipRego_No
AND		RAID.Raid_No = PRISONER.Raid_No
AND		PLANET.Planet_No = RAID.Planet_No
AND		STAR.Star_No = PLANET.Star_No

SELECT *
FROM		TWEEDLEDEER
INNER JOIN	POSITION	ON POSITION.PositionName = TWEEDLEDEER.Position
INNER JOIN	SHIP_ROSTER ON TWEEDLEDEER.Tweedle_No = SHIP_ROSTER.Tweedle_No
INNER JOIN	MEDAL		ON MEDAL.Medal = SHIP_ROSTER.Medal
INNER JOIN	SPACESHIP	ON SPACESHIP.ShipRego_No = SHIP_ROSTER.ShipRego_No
INNER JOIN	RAID		ON SPACESHIP.ShipRego_No = RAID.ShipRego_No
INNER JOIN	PRISONER	ON RAID.Raid_No = PRISONER.Raid_No
INNER JOIN	PLANET		ON PLANET.Planet_No = RAID.Planet_No
INNER JOIN	STAR		ON STAR.Star_No = PLANET.Star_No